### ISSUE TITLE
scoop bucket

### ISSUE THREAD

**Issue by NexZhu** [Ryanjiena/MetaVersion#5]
@Ryanjiena Sorry to bother you here, but I can't find another way to reach you.
I'm been using your scoop bucket to install many apps `https://github.com/Ryanjiena/scoop-apps/`,
and I just found that you've moved it or made it private?
Can you continue sharing the bucket if that's possible? Thanks! 谢谢！

**Comment by Ryanjiena** [comment]
Yes, this repo was changed to private.

**Comment by Ryanjiena** [comment]
The bucket will remain private. I will provide a deploy key so that you can upgrade package.

**Comment by NexZhu** [comment]
谢谢，key怎么获取呢，也把我添加为合作者吗？

**Comment by Ryanjiena** [comment]
1. key 后续会在 issue 里放出
2. 合作者会有仓库的写权限，目前只会考虑原仓库的协作者
