### ISSUE TITLE
仓库怎么没了?

### ISSUE THREAD

**Issue by chriscp-cat** [Ryanjiena/MetaVersion#6]
RT   为什么仓库突然没了....

**Comment by Ryanjiena** [comment]
仓库私有了

**Comment by Ryanjiena** [comment]
#5

**Comment by Ryanjiena** [comment]
主要是仓库中太多破解软件了，我想了一下以后还是不公开了，避免惹来麻烦

**Comment by Ryanjiena** [comment]
协同者没仓库权限吗......

**Comment by chriscp-cat** [comment]
没有  协同者没有任何权限

**Comment by Ryanjiena** [comment]
那有什么办法能拉取私有仓库的代码呢

**Comment by chriscp-cat** [comment]
你得把我添加为合作者 在仓库设置里

**Comment by Ryanjiena** [comment]
试了一下，需要二次验证。这个账户绑定的是那个手机在宿舍，等今晚回宿舍后我试一下

**Comment by Ryanjiena** [comment]
另外，我看一下有没有其他的办法

**Comment by chriscp-cat** [comment]
应该只有这一个办法

**Comment by JaimeZeng** [comment]
> 应该只有这一个办法

那这样人一多我不得添加的类似啊😂，并且合作者好像还有数量限制

**Comment by chriscp-cat** [comment]
别的办法都非常麻烦  比如部署秘钥 得用ssh方式克隆  或者用你账号令牌也行  就是action里用的那个  但是这样的话 就可以访问你所有私有库了 ...

**Comment by Ryanjiena** [comment]
想了一下还是用 Deploy keys ，比较方便点。另外，你用 tg 吗，tg 上聊吧

**Comment by chriscp-cat** [comment]
给你和你的bot发信息了
