### ISSUE TITLE
前几天的scoop仓库什么情况？

### ISSUE THREAD

**Issue by IsaacWangTT** [Ryanjiena/MetaVersion#7]
之前的仓库包含的软件很全面，我用了挺久的，为什么突然没了😥

**Comment by JaimeZeng** [comment]
#5 #6

**Comment by JaimeZeng** [comment]
主要是破解软件太多了，就转为私有的了

**Comment by IsaacWangTT** [comment]
> 主要是破解软件太多了，就转为私有的了

那太可惜了，可以在原仓库的基础上创建一个没有破解软件的仓库嘛😥

**Comment by Ryanjiena** [comment]
那样维护起来很麻烦的

**Comment by IsaacWangTT** [comment]
> 1. 那样维护起来很麻烦，我最初做这个 bucket 的目的仅仅是是方便我和我同学日常使用……
> 
>     2. 大多数包在 github 上基本都能找到。https://scoopsearch.github.io/ https://rasa.github.io/scoop-directory/ https://github.com/plicit/scoop-search-multisource

行吧，感谢一直以来的维护
